package com.javaguides.employee_service.service.serviceImpl;

import com.javaguides.employee_service.dto.EmployeeDto;
import com.javaguides.employee_service.entity.Employee;
import com.javaguides.employee_service.exception.ResourceNotFoundException;
import com.javaguides.employee_service.repository.EmployeeRepository;
import com.javaguides.employee_service.service.EmployeeService;
import org.modelmapper.ModelMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class EmployeeServiceImpl implements EmployeeService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmployeeServiceImpl.class);

    private EmployeeRepository employeeRepo;
    private ModelMapper mapper;
    private static final String CACHE_NAME ="employees";

    public EmployeeServiceImpl(EmployeeRepository employeeRepo, ModelMapper mapper) {
        this.employeeRepo = employeeRepo;
        this.mapper = mapper;
    }

    @Override
    //#result is a predefined variable. In Spring’s caching SpEL (Spring Expression Language),
    @CachePut(cacheNames = CACHE_NAME, key = "#result.id") //Here we don't know about id because it is auto generated by database but id we can find in returning object so here we write key = "#result.id"
    public EmployeeDto addEmployee(EmployeeDto employeeDto) {
        Employee savedEmployee = employeeRepo.save(mapper.map(employeeDto, Employee.class));
        return mapper.map(savedEmployee, EmployeeDto.class);
    }

    @Override
    @Cacheable(cacheNames = CACHE_NAME, key = "#id") //if method taking multiple argument like id and name then key = "{#id,#name}"
    public EmployeeDto getEmployeeById(long id) {
        Employee employee = employeeRepo.findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Employee", "id", String.valueOf(id))
        );

        return mapper.map(employee, EmployeeDto.class);
    }

    @Override
    public List<EmployeeDto> getEmployees() {
        return employeeRepo.findAll().stream()
                .map(employee -> mapper.map(employee, EmployeeDto.class))
                .collect(Collectors.toList());
    }

    @Override
    @CachePut(cacheNames = CACHE_NAME,key = "#id") // on the basis of id we are going to update and we know what id will be like..1 or 2 to update perticular record so we no need to write #result.id
    public EmployeeDto updateEmployeeById(long id, EmployeeDto employeeDto) {
        Employee employee = employeeRepo.findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Employee", "id", String.valueOf(id))
        );
        employee.setFirstName(employeeDto.getFirstName());
        employee.setLastName(employeeDto.getLastName());
        employee.setEmail(employeeDto.getEmail());
        employee.setDepartmentCode(employeeDto.getDepartmentCode());
        Employee updatedEmployee = employeeRepo.save(employee);
        return mapper.map(updatedEmployee, EmployeeDto.class);
    }

    @Override
    @CacheEvict(cacheNames = CACHE_NAME,key = "#id")
    public String deleteEmployeeById(long id) {
        employeeRepo.findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Employee", "id", String.valueOf(id))
        );
        employeeRepo.deleteById(id);
        return "Employee deleted successfully.";
    }
    
}
